### ISSUE TITLE
Merge this fork back into original

### ISSUE THREAD

**Issue by bobbywarner** [yamkazu/grails-database-migration#4]
@yamkazu Hey!  Thanks for all your work getting this plugin working with Grails 3 awhile ago.  I think it would be great to get this fork merged back into the original repo (https://github.com/grails-plugins/grails-database-migration).  The primary reason being is I've added a few commits to the Grails 2 version that probably should also be in Grails 3 and it just makes sense to have one repo (with two branches) going forward.  So, can you open a pull request against the master branch?  I'll create a 1.x branch for on-going maintenance of the 1.x version for Grails 2.  Please let me know.

**Comment by ColinHarrington** [comment]
:+1:

**Comment by bobbywarner** [comment]
@yamkazu There were a lot of merge conflicts, so I just took care of merging the fork into master manually.  I hope that is ok with you.  All your changes are now merged into the `master` branch in the original repo.

https://github.com/grails-plugins/grails-database-migration/commit/7545700d8b50e8a63550792b2159d044ff31c7ee
